### ISSUE TITLE
hass_client.exceptions.FailedCommand: Unknown command.

### ISSUE THREAD

**Issue by zytegalaxy** [allenporter/mcp-server-home-assistant#12]
First of all, I am very excited to try this MCP server and thanks for your contribution:

I followed the steps in the documentation and mange to add the custom component to my HA and add config to Claudia. It seems like it connects to the server but I see exceptions thrown in the log:

<img width="1440" alt="Screenshot 2024-12-07 at 11 43 13 PM" src="https://github.com/user-attachments/assets/d55b8d1e-417b-4333-bd6f-70b96eee8504">

```python
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:mcp.server:Initializing server 'mcp-home-assistant'
DEBUG:hass_client:Connecting to Home Assistant Websocket API on http://ubo-3w.local:8123/api/websocket
INFO:hass_client:Connected to Home Assistant ubo-3w.local:8123 (version 2024.11.3)
DEBUG:mcp.server:Registering handler for ListToolsRequest
DEBUG:mcp.server:Registering handler for CallToolRequest
DEBUG:mcp.server:Registering handler for PromptListRequest
DEBUG:mcp.server:Registering handler for GetPromptRequest
DEBUG:mcp.server:Received message: root=InitializedNotification(method='notifications/initialized', params=None, jsonrpc='2.0')
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0x1077996d0>
INFO:mcp.server:Processing request of type ListResourcesRequest
DEBUG:mcp.server:Response sent
DEBUG:mcp.server:Received message: <mcp.shared.session.RequestResponder object at 0x10779a710>
INFO:mcp.server:Processing request of type ListToolsRequest
DEBUG:mcp.server:Dispatching request of type ListToolsRequest
DEBUG:hass_client:Publishing message:
{'id': 2, 'type': 'mcp/tools/list'}

DEBUG:hass_client:Received message:
WSMessage(type=<WSMsgType.TEXT: 1>, data='{"id":2,"type":"result","success":false,"error":{"code":"unknown_command","message":"Unknown command."}}', extra='')

DEBUG:hass_client:Listen completed. Cleaning up
  + Exception Group Traceback (most recent call last):
  |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/stdio.py", line 83, in stdio_server
  |     yield read_stream, write_stream
  |   File "/Users/martin/Documents/mcp-server-home-assistant/mcp_server_home_assistant/server.py", line 93, in serve
  |     await server.run(read_stream, write_stream, options, raise_exceptions=True)
  |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/__init__.py", line 423, in run
  |     async with ServerSession(
  |                ~~~~~~~~~~~~~^
  |         read_stream, write_stream, initialization_options
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |     ) as session:
  |     ^
  |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/shared/session.py", line 122, in __aexit__
  |     return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
  |     raise BaseExceptionGroup(
  |         "unhandled errors in a TaskGroup", self._exceptions
  |     )
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/__init__.py", line 456, in run
    |     raise err
    |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/__init__.py", line 451, in run
    |     response = await handler(req)
    |                ^^^^^^^^^^^^^^^^^^
    |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/__init__.py", line 326, in handler
    |     tools = await func()
    |             ^^^^^^^^^^^^
    |   File "/Users/martin/Documents/mcp-server-home-assistant/mcp_server_home_assistant/server.py", line 48, in list_tools
    |     results = await client.send_command("mcp/tools/list")
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/hass_client/client.py", line 225, in send_command
    |     return await future
    |            ^^^^^^^^^^^^
    | hass_client.exceptions.FailedCommand: Unknown command.
    +------------------------------------

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "<frozen runpy>", line 198, in _run_module_as_main
  |   File "<frozen runpy>", line 88, in _run_code
  |   File "/Users/martin/Documents/mcp-server-home-assistant/mcp_server_home_assistant/__main__.py", line 38, in <module>
  |     main()
  |     ~~~~^^
  |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
  |     return self.main(*args, **kwargs)
  |            ~~~~~~~~~^^^^^^^^^^^^^^^^^
  |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/click/core.py", line 1078, in main
  |     rv = self.invoke(ctx)
  |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
  |     return ctx.invoke(self.callback, **ctx.params)
  |            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/click/core.py", line 783, in invoke
  |     return __callback(*args, **kwargs)
  |   File "/Users/martin/Documents/mcp-server-home-assistant/mcp_server_home_assistant/__main__.py", line 35, in main
  |     asyncio.run(serve(url or HOME_ASSISTANT_WEB_SOCKET_URL, token or HOME_ASSISTANT_API_TOKEN))
  |     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 194, in run
  |     return runner.run(main)
  |            ~~~~~~~~~~^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 721, in run_until_complete
  |     return future.result()
  |            ~~~~~~~~~~~~~^^
  |   File "/Users/martin/Documents/mcp-server-home-assistant/mcp_server_home_assistant/server.py", line 92, in serve
  |     async with stdio_server() as (read_stream, write_stream):
  |                ~~~~~~~~~~~~^^
  |   File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 235, in __aexit__
  |     await self.gen.athrow(value)
  |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/stdio.py", line 80, in stdio_server
  |     async with anyio.create_task_group() as tg:
  |                ~~~~~~~~~~~~~~~~~~~~~~~^^
  |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
  |     raise BaseExceptionGroup(
  |         "unhandled errors in a TaskGroup", self._exceptions
  |     )
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/__init__.py", line 456, in run
    |     raise err
    |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/__init__.py", line 451, in run
    |     response = await handler(req)
    |                ^^^^^^^^^^^^^^^^^^
    |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/__init__.py", line 326, in handler
    |     tools = await func()
    |             ^^^^^^^^^^^^
    |   File "/Users/martin/Documents/mcp-server-home-assistant/mcp_server_home_assistant/server.py", line 48, in list_tools
    |     results = await client.send_command("mcp/tools/list")
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/hass_client/client.py", line 225, in send_command
    |     return await future
    |            ^^^^^^^^^^^^
    | hass_client.exceptions.FailedCommand: Unknown command.
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Exception Group Traceback (most recent call last):
    |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/stdio.py", line 83, in stdio_server
    |     yield read_stream, write_stream
    |   File "/Users/martin/Documents/mcp-server-home-assistant/mcp_server_home_assistant/server.py", line 93, in serve
    |     await server.run(read_stream, write_stream, options, raise_exceptions=True)
    |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/__init__.py", line 423, in run
    |     async with ServerSession(
    |                ~~~~~~~~~~~~~^
    |         read_stream, write_stream, initialization_options
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     ) as session:
    |     ^
    |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/shared/session.py", line 122, in __aexit__
    |     return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
    |     raise BaseExceptionGroup(
    |         "unhandled errors in a TaskGroup", self._exceptions
    |     )
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/__init__.py", line 456, in run
      |     raise err
      |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/__init__.py", line 451, in run
      |     response = await handler(req)
      |                ^^^^^^^^^^^^^^^^^^
      |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/mcp/server/__init__.py", line 326, in handler
      |     tools = await func()
      |             ^^^^^^^^^^^^
      |   File "/Users/martin/Documents/mcp-server-home-assistant/mcp_server_home_assistant/server.py", line 48, in list_tools
      |     results = await client.send_command("mcp/tools/list")
      |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/hass_client/client.py", line 225, in send_command
      |     return await future
      |            ^^^^^^^^^^^^
      | hass_client.exceptions.FailedCommand: Unknown command.
      +------------------------------------
```

Here's my MCP server config file:

```json
{
  "mcpServers": {
    "Home-assistant": {
       "command": "/Users/martin/Documents/mcp-server-home-assistant/.venv/bin/python",
       "args": [
            "-m",
            "mcp_server_home_assistant",
            "-v",
            "-v"
       ],
       "env": {
           "HOME_ASSISTANT_WEB_SOCKET_URL": "http://ubo-3w.local:8123/api/websocket",
           "HOME_ASSISTANT_API_TOKEN": "mytoken..."
       }
    }
  }
}
```

Following the [contributing guidelines](https://github.com/allenporter/mcp-server-home-assistant/blob/ffbf63cd14569da827c2eeac116f109c00c66be1/CONTRIBUTING.md).:

```python
(mcp-server-home-assistant) ➜  mcp-server-home-assistant git:(main) uv pip install -r requirements_dev.txt
Resolved 54 packages in 309ms
Prepared 16 packages in 562ms
Installed 27 packages in 133ms
 + black==24.10.0
 + cfgv==3.4.0
 + coverage==7.6.9
 + distlib==0.3.9
 + filelock==3.16.1
 + identify==2.6.3
 + iniconfig==2.0.0
 + jinja2==3.1.4
 + markupsafe==3.0.2
 + mypy==1.13.0
 + mypy-extensions==1.0.0
 + nodeenv==1.9.1
 + packaging==24.2
 + pathspec==0.12.1
 + pdoc==15.0.0
 + pip==24.3.1
 + platformdirs==4.3.6
 + pluggy==1.5.0
 + pre-commit==4.0.1
 + pygments==2.18.0
 + pytest==8.3.4
 + pytest-aiohttp==1.0.5
 + pytest-asyncio==0.24.0
 + pytest-cov==6.0.0
 + pyyaml==6.0.2
 + ruff==0.8.2
 + virtualenv==20.28.0
(mcp-server-home-assistant) ➜  mcp-server-home-assistant git:(main) py.test
/Users/martin/Documents/mcp-server-home-assistant/.venv/lib/python3.13/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"

  warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
=================================== test session starts ===================================
platform darwin -- Python 3.13.0, pytest-8.3.4, pluggy-1.5.0
rootdir: /Users/martin/Documents/mcp-server-home-assistant
configfile: pyproject.toml
plugins: asyncio-0.24.0, cov-6.0.0, aiohttp-1.0.5, anyio-4.7.0
asyncio: mode=Mode.AUTO, default_loop_scope=None
collected 1 item                                                                          

tests/test_server.py .                                                              [100%]

==================================== 1 passed in 0.22s ===================================
```

**Comment by allenporter** [comment]
Hello, thanks for the report.  The important error appears to be the MCP server trying to connect to Home Assistant  websocket command `mcp/tools/list` and is getting `Unknown command`.

You have the screenshot of the integration added in HACS, but additionally it needs to be set up which may be why the command is not registered. 
1. Navigate to *Settings* > *Devices & Services* > *Add Integration*
1. Add the MCP integration


And we can see if that does it?

**Comment by zytegalaxy** [comment]
@allenporter I am complete newb to home assistant and apologies if I miss obvious steps. I can now see a page to setup automations and scripts but I am not sure how I should set these up and what actions I can call. 

I have a zigbee light switch switch connected to HA and I would like to give it simple commands like turn on/off the lights through Claude chat client. 

<img width="1357" alt="Screenshot 2024-12-08 at 9 20 15 PM" src="https://github.com/user-attachments/assets/6df2ad4c-bafb-4574-8253-a2565c5e55db">

**Comment by allenporter** [comment]
Did that make it so you no longer get the `unknown command` error?

Next you'll want to expose entities to conversations agents using https://www.home-assistant.io/voice_control/voice_remote_expose_devices/ -- You may want to try making sure you can control devices/entities locally through the local chat first.
