### ISSUE TITLE
Could not start MCP server Home-assistant

### ISSUE THREAD

**Issue by DoiiarX** [allenporter/mcp-server-home-assistant#14]
2024-12-12T11:36:45.997Z [error] Could not start MCP server Home-assistant: Error: spawn uv ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn uv',
  path: 'uv',
  spawnargs: [Array]
}

I meet this one error, how to deal with it?tks

**Comment by allenporter** [comment]
Do you have `uv` installed?

**Comment by allenporter** [comment]
You may want to try to get some of the examples working: https://modelcontextprotocol.io/examples if you have not already (or https://modelcontextprotocol.io/quickstart#running-the-server) as the example for this repo was in line with how they have their projects setup.

**Comment by DoiiarX** [comment]
> Do you have `uv` installed?

thanks. i solve it by `pip install uv`

**Comment by DoiiarX** [comment]
> You may want to try to get some of the examples working: https://modelcontextprotocol.io/examples if you have not already (or https://modelcontextprotocol.io/quickstart#running-the-server) as the example for this repo was in line with how they have their projects setup.

but i met another error with:

```python
DEBUG:hass_client:Listen completed. Cleaning up
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\mcp\server\stdio.py", line 83, in stdio_server
  |     yield read_stream, write_stream
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\mcp_server_home_assistant\server.py", line 93, in serve
  |     await server.run(read_stream, write_stream, options, raise_exceptions=True)
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\mcp\server\__init__.py", line 404, in run
  |     async with ServerSession(
  |                ~~~~~~~~~~~~~^
  |         read_stream, write_stream, initialization_options
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |     ) as session:
  |     ^
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\mcp\shared\session.py", line 122, in __aexit__
  |     return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  |         "unhandled errors in a TaskGroup", self._exceptions
  |     )
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\mcp\shared\session.py", line 235, in _receive_loop
    |     notification = self._receive_notification_type.model_validate(
    |         message.root.model_dump(
    |             by_alias=True, mode="json", exclude_none=True
    |         )
    |     )
    |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\pydantic\main.py", line 627, in model_validate
    |     return cls.__pydantic_validator__.validate_python(
    |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
    |         obj, strict=strict, from_attributes=from_attributes, context=context
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     )
    |     ^
    | pydantic_core._pydantic_core.ValidationError: 5 validation errors for ClientNotification
    | ProgressNotification.method
    |   Input should be 'notifications/progress' [type=literal_error, input_value='cancelled', input_type=str]
    |     For further information visit https://errors.pydantic.dev/2.10/v/literal_error
    | ProgressNotification.params.progressToken
    |   Field required [type=missing, input_value={'requestId': 94, 'reason... -2: Request timed out'}, input_type=dict]
    |     For further information visit https://errors.pydantic.dev/2.10/v/missing
    | ProgressNotification.params.progress
    |   Field required [type=missing, input_value={'requestId': 94, 'reason... -2: Request timed out'}, input_type=dict]
    |     For further information visit https://errors.pydantic.dev/2.10/v/missing
    | InitializedNotification.method
    |   Input should be 'notifications/initialized' [type=literal_error, input_value='cancelled', input_type=str]
    |     For further information visit https://errors.pydantic.dev/2.10/v/literal_error
    | RootsListChangedNotification.method
    |   Input should be 'notifications/roots/list_changed' [type=literal_error, input_value='cancelled', input_type=str]
    |     For further information visit https://errors.pydantic.dev/2.10/v/literal_error
    +------------------------------------

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "<frozen runpy>", line 198, in _run_module_as_main
  |   File "<frozen runpy>", line 88, in _run_code
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Scripts\mcp-server-home-assistant.exe\__main__.py", line 8, in <module>
  |     sys.exit(main())
  |              ~~~~^^
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
  |     return self.main(*args, **kwargs)
  |            ~~~~~~~~~^^^^^^^^^^^^^^^^^
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\click\core.py", line 1078, in main
  |     rv = self.invoke(ctx)
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
  |     return ctx.invoke(self.callback, **ctx.params)
  |            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\click\core.py", line 783, in invoke
  |     return __callback(*args, **kwargs)
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\mcp_server_home_assistant\__main__.py", line 35, in main
  |     asyncio.run(serve(url or HOME_ASSISTANT_WEB_SOCKET_URL, token or HOME_ASSISTANT_API_TOKEN))
  |     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\Doiiars\AppData\Roaming\uv\python\cpython-3.13.1-windows-x86_64-none\Lib\asyncio\runners.py", line 194, in run
  |     return runner.run(main)
  |            ~~~~~~~~~~^^^^^^
  |   File "C:\Users\Doiiars\AppData\Roaming\uv\python\cpython-3.13.1-windows-x86_64-none\Lib\asyncio\runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  |   File "C:\Users\Doiiars\AppData\Roaming\uv\python\cpython-3.13.1-windows-x86_64-none\Lib\asyncio\base_events.py", line 720, in run_until_complete
  |     return future.result()
  |            ~~~~~~~~~~~~~^^
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\mcp_server_home_assistant\server.py", line 92, in serve
  |     async with stdio_server() as (read_stream, write_stream):
  |                ~~~~~~~~~~~~^^
  |   File "C:\Users\Doiiars\AppData\Roaming\uv\python\cpython-3.13.1-windows-x86_64-none\Lib\contextlib.py", line 235, in __aexit__
  |     await self.gen.athrow(value)
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\mcp\server\stdio.py", line 80, in stdio_server
  |     async with anyio.create_task_group() as tg:
  |                ~~~~~~~~~~~~~~~~~~~~~~~^^
  |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  |         "unhandled errors in a TaskGroup", self._exceptions
  |     )
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\mcp\server\stdio.py", line 83, in stdio_server
    |     yield read_stream, write_stream
    |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\mcp_server_home_assistant\server.py", line 93, in serve
    |     await server.run(read_stream, write_stream, options, raise_exceptions=True)
    |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\mcp\server\__init__.py", line 404, in run
    |     async with ServerSession(
    |                ~~~~~~~~~~~~~^
    |         read_stream, write_stream, initialization_options
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     ) as session:
    |     ^
    |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\mcp\shared\session.py", line 122, in __aexit__
    |     return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 763, in __aexit__
    |     raise BaseExceptionGroup(
    |         "unhandled errors in a TaskGroup", self._exceptions
    |     )
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\mcp\shared\session.py", line 235, in _receive_loop
      |     notification = self._receive_notification_type.model_validate(
      |         message.root.model_dump(
      |             by_alias=True, mode="json", exclude_none=True
      |         )
      |     )
      |   File "C:\Users\Doiiars\AppData\Roaming\Claude\mcp-server-home-assistant\.venv\Lib\site-packages\pydantic\main.py", line 627, in model_validate
      |     return cls.__pydantic_validator__.validate_python(
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
      |         obj, strict=strict, from_attributes=from_attributes, context=context
      |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |     )
      |     ^
      | pydantic_core._pydantic_core.ValidationError: 5 validation errors for ClientNotification
      | ProgressNotification.method
      |   Input should be 'notifications/progress' [type=literal_error, input_value='cancelled', input_type=str]
      |     For further information visit https://errors.pydantic.dev/2.10/v/literal_error
      | ProgressNotification.params.progressToken
      |   Field required [type=missing, input_value={'requestId': 94, 'reason... -2: Request timed out'}, input_type=dict]
      |     For further information visit https://errors.pydantic.dev/2.10/v/missing
      | ProgressNotification.params.progress
      |   Field required [type=missing, input_value={'requestId': 94, 'reason... -2: Request timed out'}, input_type=dict]
      |     For further information visit https://errors.pydantic.dev/2.10/v/missing
      | InitializedNotification.method
      |   Input should be 'notifications/initialized' [type=literal_error, input_value='cancelled', input_type=str]
      |     For further information visit https://errors.pydantic.dev/2.10/v/literal_error
      | RootsListChangedNotification.method
      |   Input should be 'notifications/roots/list_changed' [type=literal_error, input_value='cancelled', input_type=str]
      |     For further information visit https://errors.pydantic.dev/2.10/v/literal_error
      +------------------------------------

```

**Comment by allenporter** [comment]
It says `Request timed out` in there. I wonder if that is an explicit error that was returned by the server? Perhaps something in home assistant error logs.
